---
- hosts: dellos6
  gather_facts: no
  tasks:
    - name: "Get Dell EMC OS6 Show version"
      community.network.dellos_command:
        commands:
          - 'show version'
      register: show_ver

    - debug:
        var: show_ver
