---
- hosts: dellos6
  connection: network_cli
  gather_facts: no

  tasks:
    - name: "Get Dell EMC OS6 Show version"
      dellos6_command:
        commands: ['show version']
      register: show_ver

    - name: Display Dell EMC OS6 Firmware Versions
      debug:
        msg: |
          Firmware Versions:
          {% for line in show_ver.stdout_lines %}
          {% if 'unit active' in line %}
          {{ line }}
          {% endif %}
          {% endfor %}

    - name: Debug Information
      debug:
        var: show_ver
